CREATE  TNALE  MENUS
(
    MENU_ID    VARCHAR2(6)    NOT NULL PRIMARY KEY
   ,MENU_NAME  VARCHAR2(100)  NOT NULL
   ,MENU_SEQ   NUMBER(5, 0)   NOT NULL   
);

INSERT INTO   MENUS  VALUES ( 'MENU01', 'JAVA', 1  );
COMMIT;



DROP TABLE MENUS1;
CREATE TABLE MENUS (
    MENU_ID     VARCHAR2(20) PRIMARY KEY,
    MENU_NAME   VARCHAR2(30),
    MENU_SEQ    NUMBER(8)
);
INSERT INTO MENUS ( MENU_ID, MENU_NAME, MENU_SEQ )
VALUES ( 'MENU01', 'JAVA' , 1);

COMMIT;

UPDATE MENUS
SET MENU_NAME = '피자'
WHERE MENU_ID = 'MENU02';
COMMIT;

